---
title: "R Notebook"
output: html_notebook
---

# Project Description

# Names of group members
Mark MacDonald
Mandip Farmahan
Sarah Henry
Vera Shcherbina

# Roles and responsibilities of each member
Mark - A&E datasets and bed occupancy analysis, working on the app
Mandip - designing and implementing the app, Covid analysis 
Sarah - patient demographics and deprivation analysis, statistics
Vera - speciality analysis and ethics
All - project planning, troubleshooting and presentation

# Brief description of dashboard topic
Our dashboard contains data from Public Health Scotland, between years 2017 to 2022 consisting of patient admission numbers by scottish health board (including A&E and inpatient data), length of stay and bed occupancy by health board. 

The data is separated by age, sex, scottish index of multiple deprivation and medical specialty.


# Stages of the project
Set expections and objectives of the project
Data exploration and choosing datasets
Planning, and KPI decision
Data wrangling preliminary analysis
Dashboard/ app wireframe
Github repository 
Dashboard/ app development
Statistics and hypothesis testing
Presentation 



# Which tools were used in the project
Zoom (daily stand-ups, mob programming, discussions)
Git/GitHub (collaboration & version control)
Excalidraw - project planning and brain storming
R - coding, charts, shiny app and hypothesis testing
slack - code sharing
Powerpoint - presentation

# How did you gather and synthesise requirements for the project?
We prioritised the information given in the brief by defining KPIs and objectives after data exploration. We further prioritised essential components and 'nice to haves'. We focused on number of episodes(admissions) and length of stay for analysis. The datasets form the structure of the app, with separate tabs for A&E, Age and Gender, SIMD and specialty. We compared results across multiple health boards. 


# Motivations for using the data you have chosen
A&E is the first point of contact for most patients in secondary care, and therefore We used the A&E dataset to answer the question about winter crisis effect. Also, it gave data by month, compared to quarterly. 
We used inpatient datasets to answer the questions about demographics and effect of Covid on acute care, because it provided data from 2017 to 2022. 
We used the hospital bed dataset to compare the mean hospital occupancy for each health board. 

# Data quality and potential bias, including a brief summary of data cleaning and transformations
According to the About tab on the dataset page/dedicated page online, the data quality is dependent on the data provider. However, we checked the data for gaps in the time series and other potential inconsistency. 

The dataset may/may not be biased because it only contains number of patients who attend hospital, and doesn't include those who are sick but see the GP or don't go to hospital. There isn't any population information for each area. The data is open source and freely available. 

To clean the datasets we used janitor package to clean up column headings and the datasets were reduced to only required columns for dashboard/ app optimisation. 

# How is the data stored and structured
[Hint: This page offers a good starting point for understanding the data structure: https://guides.statistics.gov.scot/article/34-understanding-the-data-structure]

The data is in the form of csv datasets and is linked to data with common identifiers between datasets. This means it was easy for us to connect different datasets together and obtain information from datasets. 

Benefits of storing the data like this are that all datasets can be linked together, but each data subset can be used in isolation. CSV format allows to download and upload large datasets without using much disc storage

# Ethical and legal considerations of the data
[Hint: this page contains information on the Open Government License which covers most datasets on statistic

The datasets were obtained from Public Health Scotland. It is a public sector information licensed under Open Government Data license 3.0. 
 
Data was anonymized by the provider and doesn't contain personally identifiable information, making it compliant with General Data Protection Regulation. 
 
From ethics point of view, for the sake of the project we worked on data minimisation. Only cleaned and necessary data has been uploaded to GitHub.