---
title: "Home Tab Plots"
output: html_notebook
---
#Read in Data
```{r}
read_csv(here::here("data/clean_data/"))
```

## Patient Occupancy 
```{r}
home_hb_occupancy %>% 
  filter(HB == "Scotland") %>% 
  group_by(Quarter, HB) %>% 
  summarise(avg_occupancy_percentage = round(mean(PercentageOccupancy),0)) %>% 
  ggplot(aes(x = Quarter, y = avg_occupancy_percentage, group = HB, colour = HB)) + 
  geom_line() +
  geom_point(shape = 21, size = 2) + 
  geom_vline(xintercept = c("2018Q1", "2019Q1", "2020Q1", "2021Q1", "2022Q1", "2023Q" ), linetype = 'dashed') +
  annotate("text", x = "2017Q3", y = 70, label = "2017") +
  annotate("text", x = "2018Q3", y = 70, label = "2018") +
  annotate("text", x = "2019Q3", y = 70, label = "2019") +
  annotate("text", x = "2020Q3", y = 70, label = "2020") +
  annotate("text", x = "2021Q3", y = 70, label = "2021") +
  annotate("text", x = "2022Q3", y = 70, label = "2022") +
  #annotate("text", x = "2023Q3", y = 70, label = "2023") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 5)) +
  labs(title = "Average Occupancy 2017-2023",
       x = "Health Board", 
       y = "Occupancy Percentage")
```

## Number of Episodes 

```{r}
home_hb_admissions %>% 
  filter(HB == "Scotland") %>% 
  group_by(Quarter, HB) %>% 
  summarise(no_episodes = round(mean(Episodes , na.rm = TRUE),0)) %>% 
  ggplot(aes(x = Quarter, y = no_episodes, group = HB, colour = HB)) + 
  geom_line(show.legend = FALSE) +
  geom_point(shape = 21, size = 2) + 
  geom_vline(xintercept = c("2018Q1", "2019Q1", "2020Q1", "2021Q1", "2022Q1", "2023Q" ), linetype = 'dashed') +
  annotate("text", x = "2017Q3", y = 15, label = "2017") +
  annotate("text", x = "2018Q3", y = 15, label = "2018") +
  annotate("text", x = "2019Q3", y = 15, label = "2019") +
  annotate("text", x = "2020Q3", y = 15, label = "2020") +
  annotate("text", x = "2021Q3", y = 15, label = "2021") +
  annotate("text", x = "2022Q3", y = 15, label = "2022") +
  #annotate("text", x = "2023Q3", y = 70, label = "2023") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 5)) +
  labs(title = "Number of Episodes 2017 - 2023",
       x = "Health Board", 
       y = "Number of Episodes")
```

# Average Length of Stay 

```{r}

home_hb_admissions %>%   
  filter(HB == "The Golden Jubilee National Hospital") %>% 
  group_by(Quarter, HB) %>% 
  summarise(avg_length_of_stay = round(mean(LengthOfStay , na.rm = TRUE),0)) %>% 
  ggplot(aes(x = Quarter, y = avg_length_of_stay, group = HB, colour = HB)) + 
  geom_line(show.legend = FALSE) +
  geom_point(shape = 21, size = 2) + 
  geom_vline(xintercept = c("2018Q1", "2019Q1", "2020Q1", "2021Q1", "2022Q1", "2023Q" ), linetype = 'dashed') +
  annotate("text", x = "2017Q3", y = 15, label = "2017") +
  annotate("text", x = "2018Q3", y = 15, label = "2018") +
  annotate("text", x = "2019Q3", y = 15, label = "2019") +
  annotate("text", x = "2020Q3", y = 15, label = "2020") +
  annotate("text", x = "2021Q3", y = 15, label = "2021") +
  annotate("text", x = "2022Q3", y = 15, label = "2022") +
  #annotate("text", x = "2023Q3", y = 70, label = "2023") +
  #ylim(0,15) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 5)) +
  labs(title = "Average Length of Stay 2017 - 2023",
       x = "Health Board", 
       y = "Average Length of Stay")
```



